### ISSUE TITLE
Error: manifest unknown

### ISSUE THREAD

**Issue by alx-xlx** [sablierapp/sablier#446]
I am using the following `docker-compose.yml` file

```
services:
  sablier:
    image: sablierapp/sablier:1.8.1-beta.22
    command:
      - start
      - --provider.name=docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

I ran the following command `docker compose up -d` and got the following error

```
[+] Running 1/1
 ✘ sablier Error manifest for sablierapp/sablier:1.8.1-beta.22 not found: manifest unknown: mani...                3.1s
Error response from daemon: manifest for sablierapp/sablier:1.8.1-beta.22 not found: manifest unknown: manifest unknown
```

**Comment by acouvreur** [comment]
Hi @alx-xlx 

All prio versions to 1.8.1 (including all beta) are on `acouvreur/sablier`. This project was migrated to an organization recently.

Which means you should use 1.8.1 from now on!

Does that resolves your issue ?
