### ISSUE TITLE
Caddy example not working

### ISSUE THREAD

**Issue by thueske** [sablierapp/sablier#462]
**Describe the bug**
`app-1  | Error: loading http app module: provision http: server srv1: setting up route handlers: route 1: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'sablier': provision http.handlers.sablier: parse "url=http://sablier:10000/api/strategies/dynamic": first path segment in URL cannot contain colon`

**Caddyfile (copied from example)**
```
:80 {
    route /whoami {
      sablier url=http://sablier:10000 {
        group demo
        session_duration 1m 
        dynamic {
            display_name My Whoami Service
        }
      }

      reverse_proxy whoami:80
    }
}
```

**Context**
 - Sablier version: latest
 - Provider: docker-latest
 - Reverse proxy: caddy-latest
 - Sablier running inside a container? yes

**Comment by acouvreur** [comment]
Try
```diff
:80 {
    route /whoami {
-      sablier url=http://sablier:10000 {
+      sablier http://sablier:10000 {
        group demo
        session_duration 1m 
        dynamic {
            display_name My Whoami Service
        }
      }

      reverse_proxy whoami:80
    }
}
```
